name: 'Create Workspace Variable'
description: 'Invoke Terraform API to create Variables in Terraform Cloud.'
inputs:
  tfc-workspace-id:
    description: 'Terraform workspace ID'
    required: true  
  variable-name:
    description: 'Variable name'
    required: true
  variable-value:
    description: 'Variable value'
    required: true  
secrets:    
  tfc-token:
    description: 'Terraform Cloud Token'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
