name: 'Create Terraform Workspace'
description: 'Invoke Terraform API to create workspace in Terraform Cloud.'
inputs:
  tfc-workspace:
    description: 'Terraform workspace name'
    required: true
  tfc-organization:
    description: 'Terraform organization name'
    required: true
  tfc-project-id:
    description: 'Project where the workspace will be created'
    required: true    
secrets:
  tfc-token:
    description: 'Terraform Cloud Token'
    required: true    
outputs:
  tfc-workspace-id: 
    description: 'Terraform WorkspaceId'
runs:
  using: 'node16'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'
