name: 'Create Organization Variable'
description: 'Invoke GitHub API to create variable in Organization.'
inputs:
  git-organization:
    description: 'GitHub organization name'
    required: true
  variable-name:
    description: 'Variable name'
    required: true
  variable-value:
    description: 'Variable value'
    required: true
  git-token:
    description: 'GitHub Organization Token'
    required: true
outputs:
    code:
        description: Status code
    data:
        description: Response data    
runs:
  using: 'node20'
  main: 'index.js'

branding:
  icon: 'play'  
  color: 'green'
