name: 'Initialize TFC Resources'

on:  
  workflow_call:
    inputs:
      tfc-organization:
        type: string
        required: true
      tfc-project-id: 
        type: string
        required: true
      git-project:
        type: string
        required: true
      environment: 
        type: string
        required: true
    secrets:
      tfc-token:
        required: true

permissions:
  contents: read
  id-token: write

env:
  SERVICE_TYPE: 'ecs-tasks'
    
jobs:
  createWorkspace:
    runs-on: ubuntu-20.04    
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4

      - id: tf-create-workspace
        name: "[${{ inputs.environment }}] Create Workspace"
        uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-create-workspace@main
        with:
          tfc-workspace: "${{ github.event.repository.name }}-${{ inputs.environment }}"
          tfc-organization: ${{ inputs.tfc-organization }}
          tfc-token: ${{ secrets.tfc-token}}
          tfc-project-id: ${{ inputs.tfc-project-id }}
      - id: tf-set-cluster-variable
        name: "[${{ inputs.environment }}] Set Workspace Cluster Variable"
        uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-variable-workspace@main
        with:
          tfc-workspace-id: ${{ steps.tf-create-workspace.outputs.workspaceId }}
          tfc-token: ${{ secrets.tfc-token}}
          variable-name: 'projectName'
          variable-value: ${{inputs.git-project}}
      - id: tf-set-service-variable
        name: "[${{ inputs.environment }}] Set Workspace Service Variable"
        uses: cailleach-devops/tfc-shared-actions/.github/actions/tfc/tfc-variable-workspace@main
        with:
          tfc-workspace-id: ${{ steps.tf-create-workspace.outputs.workspaceId }}
          tfc-token: ${{ secrets.tfc-token}}
          variable-name: 'serviceName'
          variable-value: ${{ github.event.repository.name }}